<a href="https://colab.research.google.com/github/Jeel88/Jeel-sPandas/blob/main/12_string_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Name": ["Jeel", "Rahul", "Amit", "Priya", "Neha"],
    "City": ["Mumbai", "Pune", "Surat", "Mumbai", "Delhi"]
})

df

    Name    City
0   Jeel  Mumbai
1  Rahul    Pune
2   Amit   Surat
3  Priya  Mumbai
4   Neha   Delhi

In [3]:
df["Name"].str.lower()

0     jeel
1    rahul
2     amit
3    priya
4     neha
Name: Name, dtype: object

In [4]:
df["Name"].str.upper()

0     JEEL
1    RAHUL
2     AMIT
3    PRIYA
4     NEHA
Name: Name, dtype: object

In [5]:
df["Name"].str.len()

0    4
1    5
2    4
3    5
4    4
Name: Name, dtype: int64

In [6]:
df["City"].str.contains("Mumbai")

0     True
1    False
2    False
3     True
4    False
Name: City, dtype: bool

In [7]:
df["Name"].str.startswith("J")

0     True
1    False
2    False
3    False
4    False
Name: Name, dtype: bool

In [8]:
df["Name"].str.endswith("h")

0    False
1    False
2    False
3    False
4    False
Name: Name, dtype: bool

In [9]:
df["City"] = df["City"].str.replace("Mumbai", "Bombay")

In [10]:
df["Name"].str.strip()

0     Jeel
1    Rahul
2     Amit
3    Priya
4     Neha
Name: Name, dtype: object

In [11]:
df

    Name    City
0   Jeel  Bombay
1  Rahul    Pune
2   Amit   Surat
3  Priya  Bombay
4   Neha   Delhi

In [12]:
df = pd.DataFrame({
    "Full_Name": ["Jeel Savaliya", "Rahul Patel", "Amit Shah"]
})

In [13]:
df["Full_Name"].str.split(" ")

0    [Jeel, Savaliya]
1      [Rahul, Patel]
2        [Amit, Shah]
Name: Full_Name, dtype: object

In [14]:
df["Full_Name"].str.split(" ").str[0]

0     Jeel
1    Rahul
2     Amit
Name: Full_Name, dtype: object

In [15]:
df = pd.DataFrame({
    "Email": [
        "jeel@gmail.com",
        "rahul@yahoo.com",
        "amit@gmail.com"
    ]
})

In [16]:
df["Email"].str.split("@").str[1]

0    gmail.com
1    yahoo.com
2    gmail.com
Name: Email, dtype: object

In [17]:
df["Email"].str.count("@")

0    1
1    1
2    1
Name: Email, dtype: int64

| Operation     | Code                     |
| ------------- | ------------------------ |
| Lowercase     | `.str.lower()`           |
| Uppercase     | `.str.upper()`           |
| Length        | `.str.len()`             |
| Contains      | `.str.contains("x")`     |
| Starts with   | `.str.startswith("x")`   |
| Ends with     | `.str.endswith("x")`     |
| Replace       | `.str.replace("x", "y")` |
| Remove spaces | `.str.strip()`           |
| Split         | `.str.split()`           |
| Count         | `.str.count("x")`        |